[package]
name = "ezbpf-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "ezbpf_core"

[dependencies]
anyhow = "1.0.86"
hex = "0.4.3"
thiserror = "1.0.61"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"

[dev-dependencies]
hex-literal = "0.4.1"